name: 自动格式化文档
on:
  pull_request:
    branches:
      - master
jobs:
  auto-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: 获取变更文件
        id: get_file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          output: '" "'
      - name: 自动格式化文档
        run: npx prettier --write "${{ steps.get_file_changes.outputs.files }}"
        continue-on-error: true
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.3.0
        with:
          commit_message: 自动格式修正
          branch: ${{ github.head_ref }}
